<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0-windows</TargetFramework>
	  <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\API\API.csproj" />
    <ProjectReference Include="..\HYMAPSOPIR\HYMAPSOPIR - VIEW.csproj" />
    <ProjectReference Include="..\Library\Library.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
